web/es/es/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('search/', include('search.urls')),
    path('admin/', admin.site.urls),
]

web/es/search/urls.py
from django.urls import path

from . import views

app_name = 'search'
urlpatterns = [
    path('search/', views.search, name='search'),
    path('search_result/', views.search_result, name='search_result'),
    path('test/', views.test, name='test'),
    path('search_log/', views.search_log, name='search_log'),
    path('search_log_clear/', views.search_log_clear, name='search_log_clear'),
    path('search_result_open/', views.search_result_open, name='search_result_open'),
    path('search_result_url_open/', views.search_result_url_open, name='search_result_url_open'),
    path('search_result_document/', views.search_result_document, name='search_result_document'),
]

web/es/search/models.py
from django.db import models


class ES(models.Model):
    MessageID = models.CharField(max_length=200)
    Date = models.CharField(max_length=200)
    From = models.CharField(max_length=200)
    To = models.CharField(max_length=200)
    Subject = models.CharField(max_length=200)
    Mime_Version = models.CharField(max_length=200)
    ContentType = models.CharField(max_length=200)
    ContentTransferEncoding = models.CharField(max_length=200)
    XFrom = models.CharField(max_length=200)
    XTo = models.CharField(max_length=200)
    Xcc = models.CharField(max_length=200)
    Xbcc = models.CharField(max_length=200)
    XFolder = models.CharField(max_length=200)
    XOrigin = models.CharField(max_length=200)
    XFileName = models.CharField(max_length=200)
    Body = models.CharField(max_length=200)

web/es/search/views.py
import math
from datetime import datetime
import json
import os

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from django.template import loader
from elasticsearch import Elasticsearch


class Params:
    def __init__(self):
        self.search_text = ""
        self.search_text_2 = ""
        self.results = []
        self.search_type = ""
        self.search_text_type = ""
        self.results_len = 0


class Result:
    def __init__(self):
        self.id = ""
        self.url = ""
        self.score = 0
        self.title = ""
        self.content = ""
        self.content_all = ""


def add_search_log(search_text, search_type):
    with open("search_log.json", 'r', encoding="utf-8") as file:  # 加载搜索历史
        search_log = json.load(file)
        file.close()
    with open("search_log.json", 'w+', encoding="utf-8") as file:  # 添加当前搜索到搜索历史
        search_log.append({"search_text": search_text, "search_type": search_type, "time": datetime.now().strftime("%Y:%m:%d:%H:%M:%S")})
        json.dump(search_log, file)
        file.close()


def search_result(request):
    # template = loader.get_template('search/search.html')
    search_text = request.POST.get('search_text')  # 获得搜索词条
    search_phrase = request.POST.get('search_phrase')
    search_regexp = request.POST.get('search_regexp')

    es = Elasticsearch()
    params = Params()
    results = []

    if search_regexp is not None:
        res = es.search(index="test", query={"bool": {
            "should": [{"wildcard": {'title': {"wildcard": search_regexp, "boost": 2}}},
                       {"wildcard": {'content': {"wildcard": search_regexp, "boost": 1}}}],
            "minimum_should_match": "50%"}}, size=10)
        params.search_text = search_regexp
        params.search_type = "Search Regexp"
        params.search_text_type = "search_regexp"
        params.results_len = res['hits']['total']['value']
        add_search_log(search_regexp, "Search Regexp")
    if search_phrase is not None:
        res = es.search(index="test", query={"bool": {
            "should": [{"match_phrase": {'title': {"query": search_phrase, "boost": 2}}},
                       {"match_phrase": {'content': {"query": search_phrase, "boost": 1}}}],
            "minimum_should_match": "50%"}}, size=10)
        params.search_text = search_phrase
        params.search_type = "Search Phrase"
        params.search_text_type = "search_phrase"
        params.results_len = res['hits']['total']['value']
        add_search_log(search_phrase, "Search Phrase")
    if search_text is not None:
        res = es.search(index="test", query={"bool": {
            "should": [{"match": {'title': {"query": search_text, "boost": 2}}},
                       {"match": {'content': {"query": search_text, "boost": 1}}}],
            "minimum_should_match": "50%"}})
        params.search_text = search_text
        params.search_type = "Search it"
        params.search_text_type = "search_text"
        params.results_len = res['hits']['total']['value']
        add_search_log(search_text, "Search text")
    # res有未定义的风险，但是逻辑上不会出现

    print("Got %d Hits" % res['hits']['total']['value'])
    # print(res)
    for hit in res['hits']['hits']:
        # print("%(timestamp)s %(author)s: %(text)s" % hit["_source"])
        # print("%(X-FileName)s" % hit["_source"])
        # print(hit["_score"])
        # print(hit["_source"])
        result = Result()
        result.url = hit["_source"]["url"]
        result.score = hit["_score"]
        result.title = hit["_source"]["title"]
        content = hit["_source"]["content"]
        result.content_all = content
        if len(content) > 100:
            result.content = content[0: 99] + "..."
        else:
            result.content = content
        results.append(result)

    with open("pr_results.json", 'r', encoding="utf-8") as file:  # 加载pr结果
        page_rank_results = json.load(file)
        file.close()
    with open("url_open_history.json", 'r', encoding="utf-8") as file:  # 加载用户浏览历史
        url_open_history = json.load(file)
        file.close()

    for result in results:
        result.score += math.log(page_rank_results[result.url] * 1000 + url_open_history[result.url] + 1)  # 将pr结果经过一定变换(ln(x+1))加到网页得分里
        # print(math.log(page_rank_results[result.url] * 1000 + 1))
        # print(url_open_history[result.url])
    results.sort(key=lambda result: result.score, reverse=True)
    params.results = results

    # return HttpResponse(results)
    return render(request, 'search/search_result.html', {'params': params})


def search_result_document(request):
    search_document_name = request.POST.get('search_document_name')
    search_document_suffix = request.POST.get('search_document_suffix')

    es = Elasticsearch()

    if search_document_name is None:
        search_document_name = ""
    if search_document_suffix is None:
        search_document_suffix = ""
    res = es.search(index="test_document", query={"bool": {
        "should": [{"wildcard": {'url': {"wildcard": "*." + search_document_suffix, "boost": 2}}},
                   {"match": {'text': {"query": search_document_name, "boost": 1}}}],
        "minimum_should_match": "50%"}}, size=10)
    results = []
    for hit in res['hits']['hits']:
        result = {"url": hit["_source"]["url"], "score": hit["_score"], "text": hit["_source"]["text"]}
        results.append(result)
    params = {"search_document_name": search_document_name, "search_document_suffix": search_document_suffix,
              "results_len": res['hits']['total']['value'], "results": results}
    add_search_log(search_document_name + "(" + search_document_suffix + ")", "Search Document")
    return render(request, 'search/search_result_document.html', {'params': params})


def search(request):
    return render(request, 'search/search.html')


def test(request):
    return render(request, 'search/test.html')


def search_log(request):
    with open("search_log.json", 'r', encoding="utf-8") as file:
        search_log = json.load(file)
        file.close()
    params = {"search_log": search_log, "search_log_len": len(search_log)}
    return render(request, 'search/search_log.html', {'params': params})


def search_log_clear(request):
    with open("search_log.json", 'w+', encoding="utf-8") as file:
        search_log = []
        json.dump(search_log, file)
        file.close()
    with open("search_log.json", 'r', encoding="utf-8") as file:
        search_log = json.load(file)
        file.close()
    params = {"search_log": search_log, "search_log_len": len(search_log)}
    return render(request, 'search/search_log.html', {'params': params})


def search_result_open(request):
    result_title = request.POST.get('result_title')
    result_content_all = request.POST.get('result_content_all')
    params = {"result_title": result_title, "result_content_all": result_content_all}
    return render(request, 'search/search_result_open.html', {'params': params})

def search_result_url_open(request):
    result_url = request.GET.get('result_url')  # 获得访问的url
    with open("url_open_history.json", 'r', encoding="utf-8") as file:  # 加载用户浏览历史
        url_open_history = json.load(file)
        file.close()
    url_open_history[result_url] += 1
    with open("url_open_history.json", 'w', encoding="utf-8") as file:  # 添加用户浏览历史
        json.dump(url_open_history, file)
        file.close()
    return HttpResponseRedirect(result_url)


web/es/search/templates/search/search.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="title" content="ScoopThemes">
    <meta name="ROBOTS" content="">
    <meta name="description" content="">
    <meta name="abstract" content="">

    <title>Search it!</title>

    {% load static %}

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/animations.css' %}">

    <!-- simple style -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body>


<div id="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <h1> Search it!</h1>
                <h2 class="subtitle">We're working hard to launch our website and we'll be ready very soon</h2>
                <br/>
                <form class="form-inline validate signup" action="{% url 'search:search_result'  %}" method="post"
                      role="form">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" name="search_text"
                               placeholder="Enter it" style="height:42px; width: 200px;border-radius: 0;border: none;">
                    </div>
                    <input type="submit" name="search" value="Search it" class="btn btn-theme">
                </form>
                <form class="form-inline validate signup" action="{% url 'search:search_result'  %}" method="post"
                      role="form">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" name="search_phrase"
                               placeholder="Enter it" style="height:42px; width: 200px;border-radius: 0;border: none;">
                    </div>
                    <input type="submit" name="search" value="Search Phrase" class="btn btn-theme">
                </form>
                <form class="form-inline validate signup" action="{% url 'search:search_result'  %}" method="post"
                      role="form">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" name="search_regexp"
                               placeholder="Enter it" style="height:42px; width: 200px;border-radius: 0;border: none;">
                    </div>
                    <input type="submit" name="search" value="Search Regexp" class="btn btn-theme">
                </form>
                <form class="form-inline validate signup" action="{% url 'search:search_result_document'  %}" method="post"
                      role="form">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" class="form-control" name="search_document_name"
                               placeholder="Enter it" style="height:42px; width: 200px;border-radius: 0;border: none;">
                        <input type="text" class="form-control" name="search_document_suffix"
                               placeholder="Enter it" style="height:42px; width: 200px;border-radius: 0;border: none;">
                    </div>
                    <input type="submit" name="search" value="Search Document" class="btn btn-theme">
                </form>
                <br/>
                <form class="form-inline validate signup" action="{% url 'search:search_log'  %}" method="post" role="form">
                    {% csrf_token %}
                    <input type="submit" name="search" value="查看历史记录" class="btn btn-theme"></input>
                </form>
            </div>
            <div class="col-sm-12 align-center">
                <ul class="social-network social-circle">
                    <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li><a href="#" class="icoGit" title="Github"><i class="fa fa-github"></i></a>
                    </li>
                    <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>


<script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
<script src="{% static 'js/jquery.form-n-validate.js' %}"></script>

</body>
</html>

web/es/search/templates/search/search_log.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="title" content="ScoopThemes">
    <meta name="ROBOTS" content="">
    <meta name="description" content="">
    <meta name="abstract" content="">

    <title>Search it!</title>

    {% load static %}

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/animations.css' %}">

    <!-- simple style -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body>


<div id="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <h1>Search Log!</h1>
                <br/>
				<ul class="list-group">
                    <ul class="list-group">
                        <li class="list-group-item">共有{{params.search_log_len}}条记录</li>
                    </ul>
                    {% for log in params.search_log %}
                	<ul class="list-group">
						<li class="list-group-item">搜索词条: {{log.search_text}}</li>
                        <li class="list-group-item">搜索类型: {{log.search_type}}</li>
						<li class="list-group-item">搜索时间: {{log.time}}</li>
					</ul>
                    {% endfor %}
                </ul>
                <br/>
                <form class="form-inline validate signup" action="{% url 'search:search_log_clear'  %}" method="post" role="form">
                    {% csrf_token %}
                    <input type="submit" name="search" value="清空历史记录!" class="btn btn-theme"></input>
                </form>
                <br>
                <form class="form-inline validate signup" action="{% url 'search:search'  %}" method="post" role="form">
                    {% csrf_token %}
                    <input type="submit" name="search" value="返回主页!" class="btn btn-theme"></input>
                </form>
                </br>
            </div>
            <div class="col-sm-12 align-center">
                <ul class="social-network social-circle">
                    <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li><a href="#" class="icoGit" title="Github"><i class="fa fa-github"></i></a>
                    </li>
                    <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>


<script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
<script src="{% static 'js/jquery.form-n-validate.js' %}"></script>

</body>
</html>

web/es/search/templates/search/search_result.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="title" content="ScoopThemes">
    <meta name="ROBOTS" content="">
    <meta name="description" content="">
    <meta name="abstract" content="">

    <title>Search it!</title>

    {% load static %}

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/animations.css' %}">

    <!-- simple style -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body>


<div id="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <h1 style="margin-bottom: 15px;margin-top: 15px;">{{params.search_type}}!</h1>
				<br/>

				<form class="form-inline validate signup" action="{% url 'search:search_result'  %}" method="post" role="form">
					{% csrf_token %}
                    <div class="form-group">
						<input type="text" value = "{{params.search_text}}" class="form-control" name="{{params.search_text_type}}" id="exampleInputEmail1" placeholder="Enter it" style="height:42px; width: 200px;border-radius: 0;border: none;">
					</div>
					<input type="submit" name="search" value="{{params.search_type}}!" class="btn btn-theme">
				</form>
                </br>
                <form class="form-inline validate signup" action="{% url 'search:search_log'  %}" method="post" role="form" style="margin-bottom: 0px;">
                    {% csrf_token %}
                    <input type="submit" name="search" value="查看历史记录" class="btn btn-theme"></input>
                </form>
				<h1 style="margin-bottom: 30px;margin-top: 30px;"> Results!</h1>
                <h4> 共有{{params.results_len}}条搜索结果</h4>
                <br/>
				<ul class="list-group">
                    {% for result in params.results %}
                	<ul class="list-group" href="Url: {{result.url}}">
                        <a href="{% url 'search:search_result_url_open' %}?result_url={{result.url}}" >
                            <li class="list-group-item">Title: {{result.title}}</li>
                            <li class="list-group-item">Content: {{result.content}}</li>
                            <li class="list-group-item">Url: {{result.url}}</li>
                            <li class="list-group-item">Score: {{result.score}}</li>
                        </a>
                        <li class="list-group-item">
                            <form class="form-inline validate signup" action="{% url 'search:search_result_open'  %}" method="post" role="form" style="margin-bottom: 0px;">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="text" class="form-control" name="result_title" value="{{result.title}}"
                                           placeholder="Enter it" style="height:42px; width: 200px;border-radius: 0;border: none;display: none">
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name="result_content_all" value="{{result.content_all}}"
                                           placeholder="Enter it" style="height:42px; width: 200px;border-radius: 0;border: none;display: none">
                                </div>
                                <input type="submit" name="search" value="查看快照" class="btn"></input>
                            </form>
                        </li>
					</ul>
                    {% endfor %}
                </ul>
                <form class="form-inline validate signup" action="{% url 'search:search'  %}" method="post" role="form">
                    {% csrf_token %}
                    <input type="submit" name="search" value="返回主页!" class="btn btn-theme"></input>
                </form>
                <br/>
            </div>
            <div class="col-sm-12 align-center">
                <ul class="social-network social-circle">
                    <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li><a href="#" class="icoGit" title="Github"><i class="fa fa-github"></i></a>
                    </li>
                    <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>


<script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
<script src="{% static 'js/jquery.form-n-validate.js' %}"></script>

</body>
</html>

web/es/search/templates/search/search_result_document.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="title" content="ScoopThemes">
    <meta name="ROBOTS" content="">
    <meta name="description" content="">
    <meta name="abstract" content="">

    <title>Search it!</title>

    {% load static %}

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/animations.css' %}">

    <!-- simple style -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body>


<div id="wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <h1 style="margin-bottom: 15px;margin-top: 15px;">Search Document!</h1>
				<br/>

                <form class="form-inline validate signup" action="{% url 'search:search_result_document'  %}" method="post"
                      role="form">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" value="{{params.search_document_name}}" class="form-control" name="search_document_name"
                               placeholder="Enter it" style="height:42px; width: 200px;border-radius: 0;border: none;">
                        <input type="text" value="{{params.search_document_suffix}}" class="form-control" name="search_document_suffix"
                               placeholder="Enter it" style="height:42px; width: 200px;border-radius: 0;border: none;">
                    </div>
                    <input type="submit" name="search" value="Search Document" class="btn btn-theme">
                </form>
                </br>
                <form class="form-inline validate signup" action="{% url 'search:search_log'  %}" method="post" role="form" style="margin-bottom: 0px;">
                    {% csrf_token %}
                    <input type="submit" name="search" value="查看历史记录" class="btn btn-theme"></input>
                </form>
				<h1 style="margin-bottom: 30px;margin-top: 30px;"> Results!</h1>
                <h4> 共有{{params.results_len}}条搜索结果</h4>
                <br/>
				<ul class="list-group">
                    {% for result in params.results %}
                	<ul class="list-group" href="Url: {{result.url}}">
                        <li class="list-group-item"><a href="Url: {{result.url}}">Url: {{result.url}}</a></li>
                        <li class="list-group-item">Text: {{result.text}}</li>
                        <li class="list-group-item">Score: {{result.score}}</li>
					</ul>
                    {% endfor %}
                </ul>
                <form class="form-inline validate signup" action="{% url 'search:search'  %}" method="post" role="form">
                    {% csrf_token %}
                    <input type="submit" name="search" value="返回主页!" class="btn btn-theme"></input>
                </form>
                <br/>
            </div>
            <div class="col-sm-12 align-center">
                <ul class="social-network social-circle">
                    <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li><a href="#" class="icoGit" title="Github"><i class="fa fa-github"></i></a>
                    </li>
                    <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>


<script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
<script src="{% static 'js/jquery.form-n-validate.js' %}"></script>

</body>
</html>

web/es/search/templates/search/search_result_open.html
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="title" content="ScoopThemes">
    <meta name="ROBOTS" content="">
    <meta name="description" content="">
    <meta name="abstract" content="">

    <title>Search it!</title>

    {% load static %}

    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/animations.css' %}">

    <!-- simple style -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body>


<div id="wrapper">
    <div class="container">
        <div class="row">
            <ul class="col-sm-12 col-md-12 col-lg-12">
                <h1>{{params.result_title}}</h1>
				<h2 class="subtitle"></h2>
				<br/>
                <ul class="list-group" href="Url: {{result.url}}">
                    <li class="list-group-item">
                        {{params.result_content_all}}
                    </li>
                </ul>
                <input type="submit" name="search" value="返回搜索结果页!" class="btn btn-theme"  onclick="javascript:history.back(-1);"></input>
                <br/>
            <div class="col-sm-12 align-center">
                <ul class="social-network social-circle">
                    <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li><a href="#" class="icoTwitter" title="Twitter"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li><a href="#" class="icoGit" title="Github"><i class="fa fa-github"></i></a>
                    </li>
                    <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>


<script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
<script src="{% static 'js/jquery.form-n-validate.js' %}"></script>

</body>
</html>